### ISSUE TITLE
Thrusters firing in wrong direction

### ISSUE THREAD

**Issue by JustBenj** [osu-uwrt/riptide_software#72]
1. Verify the sign and magnitude of the slopes in `thrusters.yml`
2. Update `pwm_controller.cpp` to include the intercepts for those slopes. This will get us outside the thrust deadband.
3. Confirm this works in the test tub before merging a fix.

**Comment by tsender** [comment]
Thrusters have been recalibrate with the copro. The thrusters were firing in the wrong direction because the vehicle experiences a force in the opposite direction as the thrust - the exact sign convention used for the thrusters was initially unclear. This has now been addressed and taken care of in the thruster controller before it publishes the command/thrust message.
